<?php

namespace Proxies\__CG__\KCC\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Product extends \KCC\Entities\Product implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function export()
    {
        $this->__load();
        return parent::export();
    }

    public function getTokens()
    {
        $this->__load();
        return parent::getTokens();
    }

    public function onPrePersist()
    {
        $this->__load();
        return parent::onPrePersist();
    }

    public function getEntityName()
    {
        $this->__load();
        return parent::getEntityName();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getIdentifier()
    {
        $this->__load();
        return parent::getIdentifier();
    }

    public function setIdentifier($id)
    {
        $this->__load();
        return parent::setIdentifier($id);
    }

    public function getLabel()
    {
        $this->__load();
        return parent::getLabel();
    }

    public function setLabel($label)
    {
        $this->__load();
        return parent::setLabel($label);
    }

    public function getManufacturer()
    {
        $this->__load();
        return parent::getManufacturer();
    }

    public function setManufacturer($manufacturer)
    {
        $this->__load();
        return parent::setManufacturer($manufacturer);
    }

    public function getReference()
    {
        $this->__load();
        return parent::getReference();
    }

    public function setReference($reference)
    {
        $this->__load();
        return parent::setReference($reference);
    }

    public function getUnit()
    {
        $this->__load();
        return parent::getUnit();
    }

    public function setUnit($unit)
    {
        $this->__load();
        return parent::setUnit($unit);
    }

    public function getKcal()
    {
        $this->__load();
        return parent::getKcal();
    }

    public function setKcal($kcal)
    {
        $this->__load();
        return parent::setKcal($kcal);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setCreated(\Webforge\Common\DateTime\DateTime $created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setUpdated(\Webforge\Common\DateTime\DateTime $updated = NULL)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getContextLabel($context = 'default')
    {
        $this->__load();
        return parent::getContextLabel($context);
    }

    public function getButtonRightIcon($context = 'default')
    {
        $this->__load();
        return parent::getButtonRightIcon($context);
    }

    public function getButtonLeftIcon($context = 'default')
    {
        $this->__load();
        return parent::getButtonLeftIcon($context);
    }

    public function equals(\Psc\Doctrine\Entity $otherEntity = NULL)
    {
        $this->__load();
        return parent::equals($otherEntity);
    }

    public function compareTo($other)
    {
        $this->__load();
        return parent::compareTo($other);
    }

    public function isNew()
    {
        $this->__load();
        return parent::isNew();
    }

    public function getEntityLabel()
    {
        $this->__load();
        return parent::getEntityLabel();
    }

    public function callSetter($field, $value)
    {
        $this->__load();
        return parent::callSetter($field, $value);
    }

    public function callGetter($field)
    {
        $this->__load();
        return parent::callGetter($field);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'label', 'manufacturer', 'reference', 'unit', 'kcal', 'created', 'updated');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}