CREATE USER 'kcc'@'localhost' IDENTIFIED BY 'eb9ep2xph82r4b';

GRANT USAGE ON * . * TO 'kcc'@'localhost' IDENTIFIED BY 'eb9ep2xph82r4b' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `kcc` ;

GRANT ALL PRIVILEGES ON `kcc` . * TO 'kcc'@'localhost';
